name: 发布二进制文件

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
      
      - name: 设置Go环境
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          
      - name: 构建多平台二进制文件
        run: |
          mkdir -p dist
          # Linux (amd64)
          GOOS=linux GOARCH=amd64 go build -o dist/omnibak-linux-amd64
          # Linux (arm64)
          GOOS=linux GOARCH=arm64 go build -o dist/omnibak-linux-arm64
          # macOS (Intel)
          GOOS=darwin GOARCH=amd64 go build -o dist/omnibak-darwin-amd64
          # macOS (Apple Silicon)
          GOOS=darwin GOARCH=arm64 go build -o dist/omnibak-darwin-arm64
          
      - name: 创建压缩包
        run: |
          cd dist
          tar -czvf omnibak-linux-amd64.tar.gz omnibak-linux-amd64
          tar -czvf omnibak-linux-arm64.tar.gz omnibak-linux-arm64
          tar -czvf omnibak-darwin-amd64.tar.gz omnibak-darwin-amd64
          tar -czvf omnibak-darwin-arm64.tar.gz omnibak-darwin-arm64
          sha256sum omnibak-*.tar.gz > checksums.txt
          
      - name: 创建Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/omnibak-linux-amd64.tar.gz
            dist/omnibak-linux-arm64.tar.gz
            dist/omnibak-darwin-amd64.tar.gz
            dist/omnibak-darwin-arm64.tar.gz
            dist/checksums.txt
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 